config/routes.rb
Rails.application.routes.draw do

  resources :arts do
    collection do
      post :sort
    end
  end

  post '/arts/:id', to: 'arts#make_featured' 

  get 'home/createPlaceholder', to: 'home#createPlaceholder'
  

  get 'sessions/new'

  get 'session/new'

  get '/signin', to: 'sessions#new'

  post '/signin', to: 'sessions#create'

  delete '/signout', to: 'sessions#destroy'


  get '/signup', to: 'users#new'

  post '/signup', to: 'users#create'

  resources :users


  get '/about', to: 'home#about'

  get '/contact', to: 'home#contact'

  get '/admin', to: 'home#admin'

  post '/admin', to: 'home#admin_update'

  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/featured_art.rb
class FeaturedArt < ApplicationRecord
  belongs_to :art
end

app/controllers/featured_arts_controller.rb
class FeaturedArtsController < ApplicationController
  before_action :set_featured_art, only: [:show, :edit, :update, :destroy]

  # GET /featured_arts
  # GET /featured_arts.json
  def index
    @arts = Art.all
    @featured_arts = FeaturedArt.all
  end

  # GET /featured_arts/1
  # GET /featured_arts/1.json
  def show
  end

  # GET /featured_arts/new
  def new
    @arts = Art.all
    @featured_art = FeaturedArt.new
  end

  # GET /featured_arts/1/edit
  def edit
  end

  # POST /featured_arts
  # POST /featured_arts.json
  def create
    @featured_art = FeaturedArt.new(featured_art_params)
    if @featured_art.save
      redirect_to action: 'index'
    else
      render :new
    end
  end

  # PATCH/PUT /featured_arts/1
  # PATCH/PUT /featured_arts/1.json
  def update
    respond_to do |format|
      if @featured_art.update(featured_art_params)
        format.html { redirect_to @featured_art, notice: 'Featured art was successfully updated.' }
        format.json { render :show, status: :ok, location: @featured_art }
      else
        format.html { render :edit }
        format.json { render json: @featured_art.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /featured_arts/1
  # DELETE /featured_arts/1.json
  def destroy
    @featured_art.destroy
    respond_to do |format|
      format.html { redirect_to featured_arts_url, notice: 'Featured art was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_featured_art
      @featured_art = FeaturedArt.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def featured_art_params
      #params.fetch(:featured_art, {})

      params.require(:featured_art).permit(:x_coord, :y_coord, :art_id)
    end
end

app/helpers/featured_arts_helper.rb
module FeaturedArtsHelper
end

app/views/featured_arts/_form.html.erb
<%= form_with(model: featured_art, local: true) do |form| %>
  <% if featured_art.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(featured_art.errors.count, "error") %> prohibited this featured_art from being saved:</h2>

      <ul>
      <% featured_art.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :x_coord %>
    <%= form.number_field :x_coord %>
  </div>

  <div class="field">
    <%= form.label :y_coord %>
    <%= form.number_field :y_coord %>
  </div>

  <div class="field">
  <%= form.collection_select(:art_id, @arts.all, :id, :title , {:include_blank =>'Wybierz obraz'}  %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/featured_arts/edit.html.erb
<h1>Editing Featured Art</h1>

<%= render 'form', featured_art: @featured_art %>

<%= link_to 'Show', @featured_art %> |
<%= link_to 'Back', featured_arts_path %>

app/views/featured_arts/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'New Featured Art', new_featured_art_path %>

<h1>Featured Arts</h1>

<div class="grid">
  <% @arts.each do |art| %>   
  <div class="item">
    <div class="item-content img-fluid img-thumbnail">
      <%= image_tag art.image %>
    </div>
  </div>
  <% end %>
</div>


<script type="text/javascript">
  var grid = new Muuri('.grid', {
    dragEnabled: true
  });
</script>

app/views/featured_arts/new.html.erb
<% provide(:title, 'Dodaj') %>

<h1>Dodaj obraz do strony głównej</h1>

<div class="row text-center text-lg-left">
	<% @arts.each do |art| %>  		
  		<div class="col-lg-3 col-md-4 col-xs-6" style="padding: 10px">		

  				<div class="img-fluid img-thumbnail">
  					<%= image_tag art.image.variant(resize: "x200"), :class => "art_image" %><br>
  					<%= art.title %><br>
  					<%= art.author %><br>
  				</div>

		</div>
 	<% end %>
</div>


<%= form_for @featured_art do |f| %>

  <div class="field">
    <%= f.label :x_coord %>
    <%= f.number_field :x_coord %>
  </div>

  <div class="field">
    <%= f.label :y_coord %>
    <%= f.number_field :y_coord %>
  </div>

  <div class="field">
    <%= f.label :art_id %>
    <%= f.number_field :art_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/featured_arts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_featured_art_path(@featured_art) %> |
<%= link_to 'Back', featured_arts_path %>