config/routes.rb
Rails.application.routes.draw do

  resources :arts do
    collection do
      post :sort
    end
  end

  post '/arts/:id', to: 'arts#make_featured' 

  get 'home/createPlaceholder', to: 'home#createPlaceholder'
  

  get 'sessions/new'

  get 'session/new'

  get '/signin', to: 'sessions#new'

  post '/signin', to: 'sessions#create'

  delete '/signout', to: 'sessions#destroy'


  get '/signup', to: 'users#new'

  post '/signup', to: 'users#create'

  resources :users


  get '/about', to: 'home#about'

  get '/contact', to: 'home#contact'

  get '/admin', to: 'home#admin'

  post '/admin', to: 'home#admin_update'

  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :verify_admin, only: [:admin, :admin_update]
  before_action :get_page

  # GET
  def index
    @arts = Art.where(:featured => true)
  end

  # GET
  def about
  end

  # GET
  def contact
  end

  # GET
  def admin
  end

  # PATCH/PUT 
  def admin_update
    if @page.update_attributes(page_params)
      redirect_to admin_path
    else
      render :admin
    end
  end

  #POST
  def createPlaceholder
    art = Art.new
    art.title = "!placeholder!"
    art.featured = true
    art.position = Art.all.where(:featured => true).count
    art.hidden = true
    if art.save
      redirect_to root_path
    else
      flash[:danger] = 'Coś poszło nie tak!'
    end
  end

  private

  def verify_admin
  	if current_user.nil?
  		redirect_to signin_path
  		flash[:danger] = 'Zaloguj się aby móc kontynuować!'
  	elsif !current_user.isAdmin
  		redirect_to root_path
  		flash[:danger] = 'Nie posiadasz uprawnień do przeglądania tej strony!'
  	end
  end

  def get_page
    @page = Page.first
    @arts = Art.where(:hidden => false)
  end

  def page_params
    params.require(:page).permit(:about, :contact)
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<% provide(:title, 'O nas') %>

<h2>O Nas</h2>

<p><%= @page.about.html_safe %></p>

app/views/home/admin.html.erb
<% provide(:title, 'Panel Administratora') %>

<h2>Panel administracyjny</h2>

<%= form_for(:page, url: admin_path) do |f| %>

<div id="about_section" class="">
	<h3>Edycja strony "O nas"</h3>	
	<%= f.trix_editor :about, :style => "background-color: white" %>
	<br>
</div>

<div id="contact_section" class="">
	<h3>Edycja strony "Kontakt"</h3>
	<%= f.trix_editor :contact, :style => "background-color: white" %>
	<br>
</div>

<div>
	<%= f.submit "Aktualizuj", class: "btn btn-primary" %>
</div>
<% end %>

<br><br>

<div class="panel panel-default">
	<table class="table">
		<thead>
			<tr>
				<th scope="col">Autor</th>
				<th scope="col">Tytuł</th>
				<th scope="col">Rok</th>
			</tr>
		</thead>

		<tbody>
			<% @arts.each do |art| %>
			<tr>
				<td><%= art.author %></td>
				<td><%= art.title %></td>
				<td><%= art.year %></td>
				<td><%= link_to 'Usuń', art, method: :delete, data: { confirm: 'Czy na pewno chcesz usunąć wpis?'}, class: "btn btn-danger" %></td>
				<td>
					<% if art.featured == true %>
						<%= link_to 'Usuń ze strony głównej', art, method: :make_featured, data: { confirm: 'Czy na pewno chcesz usunąć wpis?'}, class: "btn btn-danger" %>
					<% else %>
						<%= link_to 'Dodaj na stronie głównej', art, method: :make_featured, data: { confirm: 'Czy na pewno chcesz dodać wpis?'}, class: "btn btn-primary" %>
					<% end %>
				</td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/home/contact.html.erb
<% provide(:title, 'Kontakt') %>

<h2>Kontakt</h2>

<p><%= @page.contact.html_safe %></p>

app/views/home/index.html.erb
<% provide(:title, 'Strona główna') %>

<div style="text-align: center;">
	<h1>Strona główna - galeria sztuki</h1>
</div>

<div style="width: 50%; margin: 0 auto">
	<div class="gridster" data-url="<%= sort_arts_path %>" >
		<ul>
			<% @arts.each do |art| %>
			<li data-sizex="<%= art.data_sizex %>" data-sizey="<%= art.data_sizey %>" data-col="<%= art.data_col %>" data-row="<%= art.data_row %>" data-id="<%= art.id %>">
				<div class="gridster-box home_image_box">
					<div class="handle-resize home_image_inner">							
						<% if isAdmin? %>	
							<%= image_tag(art.image) %> 			 	        	
						<% else %>
							<%= link_to image_tag(art.image), art %>
						<% end %>
					</div>
				</div>
			</li>
			<% end %>
		</ul>
	</div>
</div>


<script type="text/javascript">

	function serializeGridster() {
		var serializeJsonArr = new Array();
		$(".gridster ul li").each(function(i) {
			var serializeJson = {};

			var id = $(this).attr('data-id');
			var sizex = $(this).attr('data-sizex');
			var sizey = $(this).attr('data-sizey');
			var row = $(this).attr('data-row');
			var col = $(this).attr('data-col');

			serializeJson["id"] = id;
			serializeJson["sizex"] = sizex;
			serializeJson["sizey"] = sizey;
			serializeJson["data-col"] = col;
			serializeJson["data-row"] = row;

			serializeJsonArr.push(serializeJson);
		})
		return serializeJsonArr;
	}

	var gridster = null;
	$(document).ready(function () {
		gridster = $(".gridster ul").gridster({
			widget_base_dimensions: ['auto', 140],
			autogenerate_stylesheet: true,
			min_cols: 1,
			max_cols: 12,
			widget_margins: [5, 5],
			resize: {
				enabled: true,

				stop: function (e, ui) {
					var homepageLayout = serializeGridster();
					console.log(homepageLayout);
					$.ajax({
						url: "/arts/sort",
						type: "POST",
						data: { data_value: JSON.stringify(homepageLayout)}
					});
				}
			},

			draggable: {
				stop: function (e, ui) {
					var homepageLayout = serializeGridster();
					console.log(homepageLayout);
					$.ajax({
						url: "/arts/sort",
						type: "POST",
						data: { data_value: JSON.stringify(homepageLayout)}
					});
				}
			}
		}).data('gridster');
		$('.gridster  ul').css({'padding': '0'});

		<% if !isAdmin? %>
		gridster.disable();
		gridster.disable_resize();
		<% end %>

	});
</script>