config/routes.rb
Rails.application.routes.draw do

  resources :arts do
    collection do
      post :sort
    end
  end

  post '/arts/:id', to: 'arts#make_featured' 

  get 'home/createPlaceholder', to: 'home#createPlaceholder'
  

  get 'sessions/new'

  get 'session/new'

  get '/signin', to: 'sessions#new'

  post '/signin', to: 'sessions#create'

  delete '/signout', to: 'sessions#destroy'


  get '/signup', to: 'users#new'

  post '/signup', to: 'users#create'

  resources :users


  get '/about', to: 'home#about'

  get '/contact', to: 'home#contact'

  get '/admin', to: 'home#admin'

  post '/admin', to: 'home#admin_update'

  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/art.rb
class Art < ApplicationRecord
	has_one_attached :image

	#scope :title_contains, -> (title) { where("title like ?", "#{title}%") }

	def self.search(title_contains)
		if title_contains
			where("title like ?", "#{title_contains}%")
		else
			all
		end
	end

	validates :author, :presence => true
	validates :title, :presence => true
	validates :year, :presence => true
	validates :image, :presence => true
end

app/controllers/arts_controller.rb
class ArtsController < ApplicationController
  before_action :verify_admin, only: [:new, :edit, :create, :update, :destroy, :make_featured]
  before_action :get_art, only: [:show, :edit, :update, :destroy, :make_featured]
  skip_before_action :verify_authenticity_token

  def index
    @arts = Art.search(params[:title_contains]).paginate(page: params[:page], :per_page => 8)
  end

  # GET /arts/1
  def show
  end

  # GET /arts/new
  def new
    @art = Art.new
  end

  # GET /arts/1/edit
  def edit
  end

  # POST /arts
  def create
    @art = Art.new(art_params)
    @art.featured = false
    if @art.save
      redirect_to @art
    else
      render :new
    end
  end

  # PATCH/PUT /arts/1
  def update
    if @art.update_attributes(art_params)
      redirect_to @art
    else
      render :edit
    end
  end

  # DELETE /arts/1
  def destroy
    if @art.destroy
      redirect_to root_path
    end
  end

  def make_featured
    if @art.featured
      @art.featured = false;
    else
      @art.featured = true;
    end

    if @art.save
      redirect_to @art
    else
      render :show
    end
  end

  #funkcja update layoutu do bazy
  def sort
    @featuredArts = JSON.parse(params[:data_value])
    @featuredArts.each do |f|
      if !f["id"].nil?
        Art.where(id: f["id"]).update_all(data_sizex: f["sizex"], data_sizey: f["sizey"], data_col: f["data-col"], data_row: f["data-row"])
      end  
    end

    head :ok
  end

  private

  def verify_admin
    if current_user.nil?
      redirect_to signin_path
      flash.now[:danger] = 'Zaloguj się!'
    elsif !current_user.isAdmin
      redirect_to root_path
      flash.now[:danger] = 'Nie masz uprawnień!'
    end
  end

  def get_art
    @art = Art.find(params[:id])
  end

  def art_params
    params.require(:art).permit(:title, :author, :image, :technique, :year, :price, :availability, :width, :height)
  end

end

app/helpers/arts_helper.rb
module ArtsHelper

end

app/views/arts/edit.html.erb
<% provide(:title, 'Edytuj') %>
<h1>Edycja obrazu</h1>

<div class="container-fluid">
	<div class="col-md-6">

		<%= form_for(@art) do |f| %>	
		
		<div class="form-group col-md-12">
			<label for="">Tytuł</label>
			<%= f.text_field :title, class: "form-control", placeholder: "Tytuł" %>
		</div>

		<div class="form-group col-md-12">
			<label for="">Autor</label>
			<%= f.text_field :author, class: "form-control", placeholder: "Autor" %>
		</div>

		<div class="form-row">
			<div class="form-group col-md-6">
				<label for="">Rok</label>
				<%= f.number_field :year, class: "form-control", placeholder: "Rok" %>
			</div>
			<div class="form-group col-md-6">
				<label for="">Technika</label>
				<%= f.text_field :technique, class: "form-control", placeholder: "Technika" %>
			</div>
		</div>

		<div class="form-row">
			<div class="form-group col-md-6">
				<label for="">Wysokość</label>
				<%= f.number_field :height, class: "form-control", placeholder: "Wysokość" %>
			</div>
			<div class="form-group col-md-6">
				<label for="">Szerokość</label>
				<%= f.number_field :width, class: "form-control", placeholder: "Szerokość" %>
			</div>
		</div>

		<div class="form-row">
			<div class="form-group col-md-2">
				<label for="">Dostępność</label>
				<%= f.check_box :availability, class: "form-control" %>
			</div>
			<div class="form-group col-md-4">
				<label for="">Cena</label>
				<%= f.number_field :price, class: "form-control", placeholder: "Cena" %>
			</div>
		</div>

		<div class="form-group col-md-12">
			<label for="">Obraz</label>
			<%= f.file_field :image, class: "col-md-12"%>
		</div>

		<div class="form-group col-md-12">
			<%= f.submit "Dodaj wpis", class: "btn btn-primary" %>
		</div>

		<% end %>
	</div>
</div>

app/views/arts/index.html.erb
<% provide(:title, 'Katalog') %>
<div id="art_nav" class="row">
	<div id="art_nav_left" class="float-left">

		<%= will_paginate @arts, :previous_label => 'Poprzednia', :next_label => 'Następna' %>
	</div>
	
	<div id="art_nav_right" class="float-right form-inline">
		<%= form_tag arts_path, :method => 'get' do %>
			<%= text_field_tag :title_contains, params[:title_contains], class: "form-control" %>
			<%= submit_tag "Szukaj", :title => nil, class: "btn btn-primary" %>

			<% if isAdmin? %>
				<%= link_to 'Dodaj wpis', new_art_path, class: "btn btn-primary" %>
			<% end %>
		<% end %>


	</div>
</div>	

<div class="row text-center text-lg-left" style="padding: 10px">
<% if @arts.any? %>
	<% @arts.each do |art| %>  		
  		<div class="col-lg-3 col-md-4 col-xs-6 art_container img-thumbnail">		
  			<%= link_to art, data: {fancybox: 'gallery', 
  										caption: "<b>"+art.title+" - "+art.author+"</b>",
  										src: image_tag(art.image).from(10).to(-1) } do %>		
  					<%= image_tag art.image, :class => "art_image" %>
  					<div class="art_overlay">
  							<div class="art_text">
  								<b><%= art.title %></b><br>
  								<%= art.author %>
  							</div>
					</div>
  			<% end %>
		</div>
 	<% end %>
<% else %>
	<p>Nie znaleziono obrazów o podanych kryteriach.</p>
<% end %>

</div>

<script type="text/javascript">
	$( '[data-fancybox]' ).fancybox({
		lang : 'pl',
		i18n : {
			'pl' : {
				CLOSE : 'Zamknij',
				ZOOM : 'Przybliż',
				DOWNLOAD : 'Pobierz',
				PREV : 'Poprzedni',
				NEXT : 'Następny',
				PLAY_START : 'Pokaz slajdów',
				THUMBS : 'Miniatury'
			}
		}
	});
	$.fancybox.defaults.buttons = ['zoom', 'close'];

	$('[data-fancybox="gallery"]').fancybox({
		caption : function( instance, item ) {
			var caption = $(this).data('caption') || '';

			if ( item.type === 'image' ) {
				caption = (caption.length ? caption + '<br />' : '') + '<a href="' + this + '" class="btn btn-primary">Przejdź do obrazu</a>' ;
			}

			return caption;
		}
	});
</script>

app/views/arts/new.html.erb
<% provide(:title, 'Nowy wpis') %>

<h1>Dodaj nowy wpis</h1>

<div class="container-fluid">
	<div class="col-md-6">
	
		<%= form_for(@art) do |f| %>	
		<div class="form-group col-md-12">
			<label for="">Tytuł</label>
			<%= f.text_field :title, class: "form-control", placeholder: "Tytuł" %>
		</div>

		<div class="form-group col-md-12">
			<label for="">Autor</label>
			<%= f.text_field :author, class: "form-control", placeholder: "Autor" %>
		</div>

		<div class="form-row">
			<div class="form-group col-md-6">
				<label for="">Rok</label>
				<%= f.number_field :year, class: "form-control", placeholder: "Rok" %>
			</div>
			<div class="form-group col-md-6">
				<label for="">Technika</label>
				<%= f.text_field :technique, class: "form-control", placeholder: "Technika" %>
			</div>
		</div>

		<div class="form-row">
			<div class="form-group col-md-6">
				<label for="">Wysokość</label>
				<%= f.number_field :height, class: "form-control", placeholder: "Wysokość" %>
			</div>
			<div class="form-group col-md-6">
				<label for="">Szerokość</label>
				<%= f.number_field :width, class: "form-control", placeholder: "Szerokość" %>
			</div>
		</div>

		<div class="form-row">
			<div class="form-group col-md-2">
				<label for="">Dostępność</label>
				<%= f.check_box :availability, class: "form-control" %>
			</div>
			<div class="form-group col-md-4">
				<label for="">Cena</label>
				<%= f.number_field :price, class: "form-control", placeholder: "Cena" %>
			</div>
		</div>

		<div class="form-group col-md-12">
			<label for="">Obraz</label>
			<%= f.file_field :image, class: "col-md-12"%>
		</div>

		<div class="form-group col-md-12">
			<%= f.submit "Dodaj wpis", class: "btn btn-primary" %>
		</div>	

		<% end %>
	</div>
</div>

<script type="text/javascript">	
</script>

app/views/arts/show.html.erb
<% provide(:title, 'Wpis') %>



<div class="col-6 col-md-8 text-center img-thumbnail">

			<%= link_to @art, data: {fancybox: 'gallery', 
  										caption: "<b>"+@art.title+" - "+@art.author+"</b>",
  										src: image_tag(@art.image).from(10).to(-1) } do %>		
  					<%= image_tag @art.image, :class => "art_image" %>
  			<% end %>
</div>

<div class="col-6 col-md-4">
	<div>
			<%= link_to 'Powrót', arts_path, class: "btn btn-primary"%>

		<%if !isAdmin? %>
			<%= link_to 'Zapytaj o dostępność', contact_path, class: "btn btn-primary"%>
		<% end %>

		<% if isAdmin? %>
			<% if @art.featured == true %>
				<%= link_to 'Usuń ze strony głównej', @art, method: :make_featured, data: { confirm: 'Czy na pewno chcesz usunąć wpis?'}, class: "btn btn-danger" %>
			<% else %>
				<%= link_to 'Dodaj na stronie głównej', @art, method: :make_featured, data: { confirm: 'Czy na pewno chcesz dodać wpis?'}, class: "btn btn-primary" %>
			<% end %>
			
			<%= link_to 'Edytuj', edit_art_path(@art), class: "btn btn-primary" %>
			<%= link_to 'Usuń', @art, method: :delete, data: { confirm: 'Czy na pewno chcesz usunąć wpis?'}, class: "btn btn-danger" %>
		<% end %>
	</div>

	<br>
	
	<div class="jumbotron" style="background-color: white;">
		<p class="art_title_author">
			<h3><%= @art.title %></h3><br>
			<%= @art.author %>
		</p><br>

		<strong>Rok: </strong><%= @art.year %><br>
		<strong>Technika: </strong><%= @art.technique %><br>
		<strong>Cena: </strong>
			<% if @art.availability %>
				<%= @art.price %> PLN<br>
			<% else %>
				Obraz nie na sprzedaż
			<% end %>
		<strong>Wymiary: </strong><%= @art.height %> x <%= @art.width %> cm
	</div>
	
</div>


<script type="text/javascript">
	$( '[data-fancybox]' ).fancybox({
		lang : 'pl',
		i18n : {
			'pl' : {
				CLOSE : 'Zamknij',
				ZOOM : 'Przybliż',
				DOWNLOAD : 'Pobierz',
				PREV : 'Poprzedni',
				NEXT : 'Następny',
				PLAY_START : 'Pokaz slajdów',
				THUMBS : 'Miniatury'
			}
		}
	});
	$.fancybox.defaults.buttons = ['zoom', 'close'];

	$('[data-fancybox="gallery"]').fancybox({
		caption : function( instance, item ) {
			var caption = $(this).data('caption') || '';

			if ( item.type === 'image' ) {
				caption = (caption.length ? caption + '<br />' : '');
			}

			return caption;
		}
	});
</script>