config/routes.rb
Rails.application.routes.draw do

  resources :arts do
    collection do
      post :sort
    end
  end

  post '/arts/:id', to: 'arts#make_featured' 

  get 'home/createPlaceholder', to: 'home#createPlaceholder'
  

  get 'sessions/new'

  get 'session/new'

  get '/signin', to: 'sessions#new'

  post '/signin', to: 'sessions#create'

  delete '/signout', to: 'sessions#destroy'


  get '/signup', to: 'users#new'

  post '/signup', to: 'users#create'

  resources :users


  get '/about', to: 'home#about'

  get '/contact', to: 'home#contact'

  get '/admin', to: 'home#admin'

  post '/admin', to: 'home#admin_update'

  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		Placeholder text in footer. Piotr Świerad 2018.
	</small>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse">
	<div class="container-fluid">
		<div class="navbar-header" style="padding-top: 7px;">
				<%#= link_to image_tag("logo.jpg"), root_path %>
		</div>
		<nav>			
			<ul class="nav navbar-nav navbar-left">
				<li style="font-size: 20px; font-style: bold"><%= link_to "Galeria Sztuki", root_path %></li>
				<li><%= link_to "Katalog", arts_path %></li>
				<li><%= link_to "O nas", about_path %></li>
				<li><%= link_to "Kontakt", contact_path %></li>			
			</ul>
		</nav>

		<nav>
			<ul class="nav navbar-nav navbar-right">
				<% if isAdmin? %>
				<li><%= link_to "Panel Administracyjny", admin_path, class: "btn btn-warning" %></li>
				<% end %>

				<% if signed_in? %>
				<li><%= link_to "Witaj #{current_user.email}", "#" %>
				<li><%= link_to "Wyloguj się", signout_path, method: :delete %></li>
				<% else %>
				<li><%= link_to "Logowanie", signin_path %>
				<li><%= link_to "Rejestracja", signup_path %></li>
				<% end %>
			</ul>
		</nav>
	</div>	
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%= yield(:title) %> | Galeriasztuki</title>
	<%= csrf_meta_tags %>

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
	<%= render 'layouts/header' %>


		<% flash.each do |type, value|%>
			<div class="alert alert-<%= type %>"><%= value %></div>
		<% end %>


	<div class="container jumbotron container-fluid" style="width: 80vw; background-color: #e6e6e6;">
		<%= yield %>
	</div>


	

	<%= render 'layouts/footer' %>
	<%= debug(params) if Rails.env.development? %>

</body>
</html>